version: '2'
services:
   php:
      build: ./docker/php-fpm
      volumes:
         - .:/app
         - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
   web:
      image: nginx:latest
      ports:
         - "8888:80"
      volumes:
         - .:/app
         - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
         - php
